@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.new_coin.App",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_977036844 { 
   	label=new_coin
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   App1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)App</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Coin1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Coin</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   HEADS: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   face: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ flip()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CoinAnimation1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CoinAnimation</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ coinModel(material: PhongMaterial, texture: Image, posX: int, posY: int, posZ: int): Cylinder</TD></TR>
<TR><TD ALIGN="LEFT" >+ coinTexture(c: Coin): Image</TD></TR>
<TR><TD ALIGN="LEFT" >+ createSpinningTimeline(cylinder: Cylinder, material: PhongMaterial, textureHeads: Image, textureTails: Image): Timeline</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleCoinAnimationStop(timelineOne: Timeline, timelineTwo: Timeline, cylinderOne: Cylinder, cylinderTwo: Cylinder, materialOne: PhongMaterial, materialTwo: PhongMaterial, coinTextureOne: Image, coinTextureTwo: Image)</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleGame(c1: Coin, c2: Coin, selectedBet: String, playerName: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GUITemplates1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GUITemplates</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ customBtn(btnText: String, posX: int, posY: int): Button</TD></TR>
<TR><TD ALIGN="LEFT" >+ customLabel(labelTxt: String, posX: int, posY: int): Label</TD></TR>
<TR><TD ALIGN="LEFT" >+ customRadioBtn(btnText: String, posX: int, posY: int): RadioButton</TD></TR>
<TR><TD ALIGN="LEFT" >+ customTextField(posX: int, posY: int): TextField</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GameWindow1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GameWindow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   playGame: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   reset: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   selectedRadioBtn: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ display(primaryStage: Stage, currentUser: User)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HashingService1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HashingService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ checkPassword(plainPassword: String, hashedPassword: String): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ hashPassword(plainPassword: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Leaderboard1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Leaderboard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ display(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LoginWindow1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LoginWindow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ display(primaryStage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PlayerVictory1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PlayerVictory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   playerName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   victoryCount: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ incrementCount()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadFile1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadFile</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ gameOutcomeData(): ArrayList&lt;PlayerRecord&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RegisterWindow1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RegisterWindow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ display(primaryStage: Stage)</TD></TR>
<TR><TD ALIGN="LEFT" >- isEmpty(str: String): Boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SQL1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SQL</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addUser(user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkDuplicateUser(username: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserByUsername(authUsername: String): User</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Twoup1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Twoup</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   resultOfGame: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ playGame(c1: Boolean, c2: Boolean, currentBet: String, playerName: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VictoryCounter1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VictoryCounter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ countPlayerVictories(records: ArrayList&lt;PlayerRecord&gt;): ArrayList&lt;PlayerVictory&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- findPlayerInList(list: ArrayList&lt;PlayerVictory&gt;, playerName: String): PlayerVictory</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WriteFile1227026783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WriteFile</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- dateNow(): Date</TD></TR>
<TR><TD ALIGN="LEFT" >+ writeFileScores(data: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
App1227026783 -> LoginWindow1227026783[label="start() -> display()"];
CoinAnimation1227026783 -> Twoup1227026783[label="handleGame() -> playGame()"];
GameWindow1227026783 -> Leaderboard1227026783[label="display() -> display()"];
Leaderboard1227026783 -> ReadFile1227026783[label="display() -> gameOutcomeData()"];
Leaderboard1227026783 -> VictoryCounter1227026783[label="display() -> countPlayerVictories()"];
LoginWindow1227026783 -> GameWindow1227026783[label="display() -> display()"];
LoginWindow1227026783 -> HashingService1227026783[label="display() -> checkPassword()"];
LoginWindow1227026783 -> RegisterWindow1227026783[label="display() -> display()"];
LoginWindow1227026783 -> SQL1227026783[label="display() -> getUserByUsername()"];
RegisterWindow1227026783 -> HashingService1227026783[label="display() -> hashPassword()"];
VictoryCounter1227026783 -> PlayerVictory1227026783[label="countPlayerVictories() -> incrementCount()"];
    
}
@enduml